### ISSUE TITLE
The URL must be one of scheme file or data

### ISSUE THREAD

**Issue by fhc93** [isomorphic-microfrontends/root-config#32]
Hello,

I was trying to see how this example works but when I go to localhost:9000 after running the yarn develop command the server fails and shows this error
![iso_error](https://user-images.githubusercontent.com/32887295/165638786-38562a16-dba7-45b9-bffe-670df9c60972.jpg)

I tried running the projects on windows and mac and both have the same error.

Any idea on how to fix this?

**Comment by TomStrepsil** [comment]
I think this is caused by changes in Node JS.

I managed to get things to work with Node 17 by updating a yarn script thus (adding `--experimental-network-imports`):
```json
"develop:node": "nodemon -e js,ejs,html --experimental-network-imports --experimental-loader @node-loader/core server/server.js",
```
...and adding the following to `server/server.js`:
```javascript
import { setDefaultResultOrder } from "dns";
setDefaultResultOrder('ipv4first');
```

**Comment by nzinovyev19** [comment]
> I think this is caused by changes in Node JS.
> 
> I managed to get things to work with Node 17 by updating a yarn script thus (adding `--experimental-network-imports`):
> 
> ```json
> "develop:node": "nodemon -e js,ejs,html --experimental-network-imports --experimental-loader @node-loader/core server/server.js",
> ```
> 
> ...and adding the following to `server/server.js`:
> 
> ```js
> import { setDefaultResultOrder } from "dns";
> setDefaultResultOrder('ipv4first');
> ```

Yes, it helps, thanks)
Or like another solution one can downgrade Node for 14v.

**Comment by prashantsharmain** [comment]
For me, it works only when I use Node `14.20.0`.

I ran into the following initialisation error with Node `17.9.1` and `--experimental-network-imports` flag:
```
[develop:node] (node:37444) DeprecationWarning: Obsolete loader hook(s) supplied and will be ignored: getFormat, getSource, transformSource
[develop:node] App is hosted at http://localhost:9000/
[develop:webpack] ℹ ｢wds｣: Project is running at http://localhost:9876/
[develop:webpack] ℹ ｢wds｣: webpack output is served from /
[develop:webpack] ℹ ｢wds｣: Content not from webpack is served from /Users/kanishksharma/Documents/prashant_backup_july_2022/projects/learn/abc-racing/root-config
[develop:webpack] ℹ ｢wds｣: 404s will fallback to /index.html
[develop:webpack] node:internal/crypto/hash:67
[develop:webpack]   this[kHandle] = new _Hash(algorithm, xofLen);
[develop:webpack]                   ^
[develop:webpack] 
[develop:webpack] Error: error:0308010C:digital envelope routines::unsupported
[develop:webpack]     at new Hash (node:internal/crypto/hash:67:19)
[develop:webpack]     at Object.createHash (node:crypto:135:10)
[develop:webpack]     at module.exports (/Users/kanishksharma/Documents/prashant_backup_july_2022/projects/learn/abc-racing/root-config/node_modules/webpack/lib/util/createHash.js:135:53)
[develop:webpack]     at NormalModule._initBuildHash (/Users/kanishksharma/Documents/prashant_backup_july_2022/projects/learn/abc-racing/root-config/node_modules/webpack/lib/NormalModule.js:417:16)
[develop:webpack]     at handleParseError (/Users/kanishksharma/Documents/prashant_backup_july_2022/projects/learn/abc-racing/root-config/node_modules/webpack/lib/NormalModule.js:471:10)
[develop:webpack]     at /Users/kanishksharma/Documents/prashant_backup_july_2022/projects/learn/abc-racing/root-config/node_modules/webpack/lib/NormalModule.js:503:5
[develop:webpack]     at /Users/kanishksharma/Documents/prashant_backup_july_2022/projects/learn/abc-racing/root-config/node_modules/webpack/lib/NormalModule.js:358:12
[develop:webpack]     at /Users/kanishksharma/Documents/prashant_backup_july_2022/projects/learn/abc-racing/root-config/node_modules/loader-runner/lib/LoaderRunner.js:373:3
[develop:webpack]     at iterateNormalLoaders (/Users/kanishksharma/Documents/prashant_backup_july_2022/projects/learn/abc-racing/root-config/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
[develop:webpack]     at Array.<anonymous> (/Users/kanishksharma/Documents/prashant_backup_july_2022/projects/learn/abc-racing/root-config/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
[develop:webpack]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[develop:webpack]   library: 'digital envelope routines',
[develop:webpack]   reason: 'unsupported',
[develop:webpack]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[develop:webpack] }
[develop:webpack] 
[develop:webpack] Node.js v17.9.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by danfilg** [comment]
@asos-tomp or @prashantsharmain did it work for you? were you able to run the MFes?
