### ISSUE TITLE
Import Map 403 Forbidden Error Running on Local

### ISSUE THREAD

**Issue by CodingFlow** [isomorphic-microfrontends/root-config#44]
I tried running the project locally without modifications using Node.js 14.16.1 and get errors related to import map and HTTP status response 403 forbidden when trying to access the app on localhost:9000 in the browser:

```console
[develop:node] (node:19444) UnhandledPromiseRejectionWarning: Error: Import Map at https://storage.googleapis.com/isomorphic.microfrontends.app/importmap.json responded with HTTP status 403
[develop:node]     at file:///C:/Users/Blue/source/repos/Git/external/isomorphic-microfrontends/root-config/node_modules/single-spa-web-server-utils/lib/import-map-poller.js:70:17
[develop:node]     at runMicrotasks (<anonymous>)
[develop:node]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[develop:node] (node:19444) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 275)
```

I wanted to get a better idea of how Single SPA can used with SSR and different frameworks so I can make it work for any framework. Any ideas on how to get this to work or point me to a working example?

**Comment by MagedWilliamdevlink** [comment]
its back up again, i have noticed the live example and the import maps up and running again last month or so
